### ISSUE TITLE
Simplify Scheduler code base

### ISSUE THREAD

**Issue by YangKeao** [pingcap-incubator/tinykv#58]
## Schedule Part

At present, all sent messages follow these flow:

```
request -> (get store/bind stream/get region) -> raft cluster HandleRegionHeartbeat -> Dispatch

drivePushOperator -> PushOperators -> Dispatch -> SendScheduleCommand

PromoteWaitingOperator -> addOperatorLocked -> SendScheduleCommand
```

All operators are created in these flow:

```
Scheduler runScheduler -> AddWaitingOperator 

patrolRegions -> AddWaitingOperator
```

We can simplify scheduler in these points:

- Remove merge operator and all related changes (because merge operation has two operator)  

- Simplify the total routine. Maybe the simplest way: `request -> operator`. Delete waiting queue, pushDriver... Should we have a waiting queue (or simply cancel all exceeded operation?)

**schedule**:

- [x]    checker: make replica checker only checks down peer and offline peer( or just remove replica_checker) #61 
- [ ]    filter: remove unnecessary filters #62
- [x]    operator: only keep TransferLeader, AddPeer, RemovePeer #61
- [ ]    opt: remove these options #62
- [x]    placement: remove it #61
- [x]    remove waiting queue, pushDriver #61

**schedulers**:

- [x]    remove label scheduler #61
- [x]    simplify balance region scheduler #62

**Comment by Connor1996** [comment]
Good job!

Something to add:
**schedule:**
- checker: make replica checker only checks down peer and offline peer( or just remove replica_checker)
- filter: remove unnecessary filters
- operator: only keep TransferLeader, AddPeer, RemovePeer
- opt: remove these options
- placement: remove it
- remove waiting queue, pushDriver

**schedulers:**
- remove label scheduler
- simplify balance region scheduler
